[font]
size = 12

builtin_box_drawing = true

normal = { family = "CaskaydiaMono Nerd Font", style = "SemiBold" }
bold = { family = "CaskaydiaMono Nerd Font", style = "Bold" }
italic = { family = "CaskaydiaMono Nerd Font", style = "Italic" }
bold_italic = { family = "CaskaydiaMono Nerd Font", style = "Bold Italic" }
