backend = "Windows WASAPI"
bufferSizeSamples = 512
[input]
device = "Stereo Mix (Realtek(R) Audio)"
suggestedLatencySeconds = 0.0
[output]
device = "Headphones (Realtek(R) Audio)"
suggestedLatencySeconds = 0.0
