backend = "Windows WASAPI"
bufferSizeSamples = 1024
[input]
device = "Microphone (MIXLINE Stream)"
suggestedLatencySeconds = 0.0
[output]
device = "Headphones (Realtek(R) Audio)"
suggestedLatencySeconds = 0.0
