backend = "Windows WASAPI"
bufferSizeSamples = 1024
[input]
device = "Headphones (Realtek(R) Audio) [Loopback]"
suggestedLatencySeconds = 0.0
[output]
device = "Headphones (Realtek(R) Audio)"
suggestedLatencySeconds = 0.0
